#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
RUN curl -sL https://deb.nodesource.com/setup_10.x |  bash -
RUN apt-get install -y nodejs

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
RUN curl -sL https://deb.nodesource.com/setup_10.x |  bash -
RUN apt-get install -y nodejs
WORKDIR /src
COPY ["ClassicCoreAndReactApp/ClassicCoreAndReactApp.csproj", "ClassicCoreAndReactApp/"]
RUN dotnet restore "ClassicCoreAndReactApp/ClassicCoreAndReactApp.csproj"
COPY . .
WORKDIR "/src/ClassicCoreAndReactApp"
RUN dotnet build "ClassicCoreAndReactApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ClassicCoreAndReactApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ClassicCoreAndReactApp.dll"]